repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 0671d8ab202c4ac093b78433ae5baf74f3fc7246 # v0.15.15
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: local
  hooks:
    - id: pyright
      name: pyright
      entry: uv run pyright
      language: system
      types: [python]
      pass_filenames: false
